name: Build

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, 'ci skip')"
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '18'
      - name: Install dependencies
        run: yarn install --frozen-lockfile
      - name: Build chrome
        run: yarn build:chrome
      - name: Upload chrome
        uses: actions/upload-artifact@v3
        with:
          name: chrome
          path: |
            dist/
            stats.html
      - name: Build firefox
        run: yarn build:firefox
      - name: Upload firefox
        uses: actions/upload-artifact@v3
        with:
          name: firefox
          path: |
            dist/
            stats.html
